# inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5.3
  NewCops: enable
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Enabled: true
Security:
  Enabled: true
Style/FormatStringToken:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Encoding:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Style/HashSyntax:
  EnforcedStyle: ruby19
Naming/PredicateName:
  Enabled: false
Naming/HeredocDelimiterNaming:
  Enabled: false
Metrics/MethodLength:
  Max: 75 # 25 in conduit
Layout/LineLength:
  Max: 120
Metrics/AbcSize:
  Enabled: false
Metrics/ModuleLength:
  Max: 120
Metrics/ClassLength:
  Max: 300 # 125 in conduit
Metrics/ParameterLists:
  CountKeywordArgs: false
Lint/AmbiguousBlockAssociation:
  Enabled: true
Lint/SuppressedException:
  AllowComments: true
Style/GlobalVars:
  AllowedVariables: ['$basedir']
Style/OptionalBooleanParameter:
  Enabled: false
Style/SafeNavigation:
  Enabled: false # requires 2.3
Style/SoleNestedConditional:
  Exclude:
    - lib/kdi/kdi_helpers.rb
    - tasks/snyk/snyk.rb
    - tasks/snyk_findings/snyk_findings.rb
Style/TrailingCommaInArguments:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
