
name: Blackduck

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: BlackDuck
    steps:
      - uses: philips-labs/blackduck-scanner-action@v1
        with:
          token: ${{ secrets.BLACKDUCK_TOKEN }}
          projectName: Toolkit
          versionPrefix: 1.0
          url: ${{ secrets.BLACKDUCK_URL }}
          sourcePath: /
          extraArgs: --detect.ruby.include.dev.dependencies=false

