
name: Blackduck

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
   BlackDuck-Scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Toolkit Repo
      uses: actions/checkout@v2
      with:
        repository: KennaPublicSamples/toolkit
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install dependencies
      run: bundle install --without development test
    - name: Synopsys Detect
      uses: blackducksoftware/github-action@2.0.0
      with:
        args: '--blackduck.url="${{ secrets.BLACKDUCK_URL}}" --blackduck.api.token="${{ secrets.BLACKDUCK_TOKEN}}"'
