# This is a basic workflow to help you get started with Actions

name: Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@master
    - name: lint
      uses: luke142367/Docker-Lint-Action@v1.0.0
      with:
        target: Containerfile
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
