name: Native-Ruby-Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Native-Ruby-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Toolkit Repo
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
      - name: Install dependencies
        run: bundle install --without 'development test'
      - name: Smoke test
        run: ruby toolkit.rb task=help
      - name: Install dev/test dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rspec
      - name: Generate test summary
        # generate summary even if specs fail
        if: always()
        run: bundle exec rspec-gh-summary >> $GITHUB_STEP_SUMMARY

